config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root "posts#index"
  resources :posts
  get 'search', to: 'posts#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :move_to_index, except: [:index, :show]

  def index
    @q = Post.ransack(params[:posts])
    @category = Category.all
    @posts = @q.result(distinct: true).order(id: :desc)
  end

  def search
    @q = Post.search(search_params)
    @posts = @q.result(distinct: true).order(id: :desc)
  end

  def new
    @posts = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to(root_path)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:image, :name, :text)
  end

  def search_params
    params.require(:q).permit(:name_cont, :category_eq)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_footer.html.haml
.footer
  .text
    Copyright © Insectagram

app/views/layouts/_header.html.haml
.head
  .title
    = link_to'Insectagram', root_path
  .contents
    - if user_signed_in?
      .content
        = link_to "LOG OUT",destroy_user_session_path, method: :delete, class: 'log-out'
        = link_to new_post_path do
          =image_tag 'pict/icon_camera.png',size:"30x30",alt:"icon_camera",class:"exhibitionBtn__icon"
    - else
      .content
        = link_to "LOG IN", new_user_session_path, class: 'log-in'
        = link_to "SIGN UP", new_user_registration_path, class: 'sign-up'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Insect2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    = yield
    = render 'layouts/footer'

app/views/posts/index.html.haml
-# .research
-#   = search_form_for(@q, url:search_path) do |f|
-#     = f.search_field :name_cont, placeholder:"種名で検索"
-#     = f.collection_select :ordo_eq, @ordos, :id, :name, :include_blank => '分類を指定'
-#     = f.submit 
.top
  .text
    LET'S POST YOUR
    %br
    "COLLECTED INSECT"!
.PostPage
  .posts
    - @posts.each do |post|
      .post
        .image
          =link_to post do
            =image_tag post.image.url if post.image.present?
        =link_to post do
          .info 
            #{post.name}
            %br
            #{post.text} 
.bottom
  .text
    LET'S POST YOUR
    %br
    "COLLECTED INSECT"!

app/views/posts/new.html.haml
.post-content
  .post-content-send
    = form_with(model: @posts, local: true) do |form|
  
      = form.file_field :image, placeholder:"Image Url"
      = form.select :category, [ ["分類を選択",""],["鞘翅目","1"],["鱗翅目","2"],["膜翅目","3"],["蜻蛉目","4"],["半翅目","5"],["直翅目","6"],["双翅目","7"],["螳螂目","8"]]
      = form.text_field :name, placeholder:"種名"
      = form.text_field :text, placeholder:"採集地" 
      = form.submit "SEND" , class: "submit"
      
  -# .map
  -#   .map-form
  -#     %p
  -#       %form{:onsubmit => "return false;"}
  -#       %input#address{:type => "text", :value => "株式会社div"}/
  -#       %button#map_button{:type => "button", :value => "検索"} 検索
      
  -#   #map
  -#   %p
  -#     緯度
  -#     %input#lat{:type => "text", :value => ""}/
      
  -#     経度
  -#     %input#lng{:type => "text", :value => ""}/
  -#   :javascript
      
  -#     let map
  -#     function initMap() {    
  -#       var geocoder = new google.maps.Geocoder()
  -#       var map = new google.maps.Map(document.getElementById('map'), {
  -#         center: {lat: 35.662699, lng:139.700557},
  -#         zoom: 14,
  -#         mapTypeId: google.maps.MapTypeId.ROADMAP
  -#       });
  -#       var marker = new google.maps.Marker({
  -#         position:  {lat: 35.662699, lng:139.700557},
  -#         map: map
  -#       });
  -#     }
  -#     let geocoder
  -#     function codeAddress(){
  -#       var geocoder = new google.maps.Geocoder()
  -#       var inputAddress = document.getElementById('address').value;
  -#         geocoder.geocode( { 'address': inputAddress}, function(results, status) {
  -#           if (status == 'OK') {
  -#             map.setCenter(results[0].geometry.location);
  -#             var marker = new google.maps.Marker({
  -#               map: map,
  -#               position: results[0].geometry.location
  -#             });
  -#           } else {
  -#             alert('該当する結果がありませんでした：' + status);
  -#           }
  -#         });   
        
  -#     }
  -#     window.onload = function(){
  -#       initMap(); 
  -#     };

app/views/posts/show.html.haml
.showPage
  .showPost
    .showPost__image
      = image_tag @post.image.url
    .showPost__info
      .showPost__info__name
        = @post.name
      .showPost__info__text
        = @post.text
    .showPost__destroy
      =link_to post_path(@post), method: :delete do
        削除